services:
  - type: web
    name: ferremas
    env: python
    runtime: python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 